### ISSUE TITLE
Number of trainable parameters

### ISSUE THREAD

**Issue by JonathanCMitchell** [MadryLab/cifar10_challenge#20]
I logged out the number of trainable parameters here and I received 45,901,914 params. 
Using this function
```np.sum([np.prod(v.get_shape().as_list()) for v in tf.trainable_variables()])```

But when I look at the number of trainable parameters in the wideresnet from their original paper: https://arxiv.org/abs/1605.07146 I see 36.5M. Why is yours so much more?
![trainable_params_wideresnet](https://user-images.githubusercontent.com/13068956/69467117-88593280-0d3b-11ea-959d-922756a34aff.png)

Also, is there a pytorch version of this network? I noticed you referred to the Robustness platform, but I don't see an actual implementation of the exact same network mentioned here in that repository here: https://github.com/MadryLab/robustness/blob/master/robustness/cifar_models/resnet.py I only see a ResNet 18 wide but that's it.

Thanks,

**Comment by dtsip** [comment]
You are right, the architecture here is not exactly the same as a typical "wide ResNet". We started from a standard ResNet architecture from the Tensorflow tutorial and modified it to be 10x wider for most blocks.

In https://github.com/MadryLab/robustness you can find a pre-trained robust ResNet50. It is not the exact same architecture as the model in this repo, but it turns out to actually be more robust.
