### ISSUE TITLE
Overflow when random_restart is false

### ISSUE THREAD

**Issue by hanboa** [MadryLab/cifar10_challenge#21]
We believe there is overflow occurring in [pgd_attack.py](https://github.com/MadryLab/cifar10_challenge/blob/master/pgd_attack.py#L56) when `random_start `is `False`. Because `x` is of type `uint8`, `x` will overflow when the gradient step is added to it owing to the unsafe add. To fix this, we propose the change below. (Note: there is a similar issue with `x_nat` when the `step_size` in [config.json](https://github.com/MadryLab/cifar10_challenge/blob/master/config.json#L28) is an integer.)

Interestingly, when we run 20-step PGD with no random start, step size of 2.0, and our fix, the adversarially-trained model achieves an adversarial accuracy of 45.81%. That is really close to the _20-step PGD on the cross-entropy loss with 10 random restarts_ white-box leaderboard result (45.21%). We also found that increasing the number of steps to 100 with a step size of 1.0 yields an adversarial accuracy of 45.37%, closing the gap further. 

It seems that random-starts/random-restarts are unnecessary when you attack an adversarially-trained model. Any difference between a random start and non-random start would imply that either the attack needs more iterations or that gradient masking is occurring for those examples. We are currently investigating how this issue affects adversarial training. 

**Proposed change:**
```
diff --git cifar10_input.py cifar10_input.py
index aa2eec4..334bba5 100644
--- cifar10_input.py
+++ cifar10_input.py
@@ -42,7 +42,7 @@ class CIFAR10Data(object):
         eval_filename = 'test_batch'
         metadata_filename = 'batches.meta'

-        train_images = np.zeros((50000, 32, 32, 3), dtype='uint8')
+        train_images = np.zeros((50000, 32, 32, 3), dtype='float32')
         train_labels = np.zeros(50000, dtype='int32')
         for ii, fname in enumerate(train_filenames):
             cur_images, cur_labels = self._load_datafile(os.path.join(path, fname))
```

**Comment by dtsip** [comment]
You are actually right, there is an issue with uint8 when `random_start` is `False`. Specifically, if your step size is a float (less than one), then the PGD step has no effect since the float is cast to an int. Note that this is not an issue of overflow, but rather an issue of incorrect casting.

Interestingly, this would not really be an issue in the current codebase since when `epsilon` is a float (e.g., `8.0`) then the clipping operation will result in `x` becoming float and hence all the following PGD steps work correctly.

I just pushed a fix in commit 65536bfcaa5ef84b4eef3285da150412d69022d3 by casting `x` to float directly when `random_start: False`.

Note that, overall, this should not affect any of the reported results since we always use a random start. Also, it should not affect anything when the step size is an integer. From what I understand, your improved attack comes from using a larger step size (when running 20-step PGD we used a step size of 1).
